on:
  push:
    branches: [ master ]
    tags:
      - 'v*' ## Push events to matching v*, i.e. v1.0

name: Create Release

jobs:
  build:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      steps:
        - uses: actions/checkout@master
        - name: Archive Release
          uses: thedoctor0/zip-release@master
          with:
            filename: 'blorm.zip'
            exclusions: '*.git* /*node_modules/* .editorconfig'
            directory: 'blorm'