on:
  push:
    branches: [ master ]
#    tags:
#      - 'v*' ## Push events to matching v*, i.e. v1.0, v20.15.10

name: Create Release

jobs:
  build:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Remove projectfiles and dirs
        run: |
          ls -lsa
          rm -R .github .gitignore .DS_Store
          ls -lsa
          git config --global user.email "gitaction@blorm.io"
          git config --global user.name "github actions"
          git commit -m "removed .github .gitignore .DS_Store" -a
        shell: bash

      - name: Create Release
        uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "latest"
          prerelease: true
          title: "Development Build - we are still Beta"
          files: |
            assets
            classes
            lib
            templates
            blorm.php
            config.php
            REAME.md