# This is a basic workflow to help you get started with Actions
name: Build Release tar and zip

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
    tags:
      - 'v*' ## Push events to matching v*, i.e. v1.0

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: make the blorm dir
        run: |
          mkdir blorm
          mkdir blorm/assets

      # Runs a set of commands using the runners shell
      - name: copy assets to blorm
        run: |
          cp -R assets/css blorm/assets
          cp -R assets/icons blorm/assets
          cp -R assets/images blorm/assets
          cp -R assets/js blorm/assets
          cp -R config blorm
          cp -R lib blorm
          cp blorm.php blorm
          cp uninstall.php blorm

      - name: zip the assets
        run: |
          zip -r blorm.zip blorm
          tar -cvf blorm.tar blorm

      - name: Create Release
        uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: false
          automatic_release_tag: "latest"
          title: "Latest Build"
          files: |
            blorm.zip
            blorm.tar

